language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
cache:
  directories:
    - node_modules

sudo: false

notifications:
  email:
    on_success: always

before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fatarrow' ]; then cd .. && eval "mv $currentfolder generator-fatarrow" && cd generator-fatarrow; fi
