language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fatarrow' ]; then cd .. && eval "mv $currentfolder generator-fatarrow" && cd generator-fatarrow; fi